
export const ACTION_TYPES = {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    AUTH: 'AUTH',
    REFRESH: 'REFRESH',
    ONCHANGE: 'ONCHANGE',
    SIGNUP: 'SIGNUP',
    SET_LOGIN_ERR: 'SET_LOGIN_ERR',
    SET_SIGNUP_ERR: 'SET_SIGNUP_ERR',
    SET_MINIPLAYER: 'SET_MINIPLAYER',
    SHOWCALL: 'SHOWCALL'
}